namespace Blaizio.Cli.Core.Projects;

/// <summary>
/// Writes a <c>global using</c> for the headless Base/Icons namespace into the output directory.
/// Copied component <c>.cs</c> files reference types in the <c>Blaizio</c> namespace (Base primitives,
/// <c>Icon</c>/<c>Icons</c>) that the originals resolved by namespace nesting (<c>Blaizio.Ui</c> →
/// <c>Blaizio</c>). The namespace rewrite breaks that chain, and <c>.cs</c> files don't see
/// <c>_Imports.razor</c> — so a project-wide global using restores resolution for C# and generated
/// Razor alike.
/// </summary>
public static class GlobalUsingsWriter
{
    /// <summary>The generated file name (project-relative to the output dir).</summary>
    public const string FileName = "Blaizio.GlobalUsings.g.cs";

    /// <summary>Ensure the global using file exists under the output dir. Returns true when written.</summary>
    public static async Task<bool> EnsureAsync(
        string projectDir,
        string outputDir,
        string baseNamespace,
        CancellationToken ct = default)
    {
        var dir = Path.Combine(projectDir, outputDir);
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, FileName);

        var line = $"global using {baseNamespace};";
        var content =
            "// <auto-generated /> Written by the Blaizio CLI so copied components resolve the Base/Icons namespace." +
            Environment.NewLine + line + Environment.NewLine;

        if (File.Exists(path) && (await File.ReadAllTextAsync(path, ct)).Contains(line, StringComparison.Ordinal))
            return false;

        await File.WriteAllTextAsync(path, content, ct);
        return true;
    }
}
