<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" Version="2.9.0" />
    <PackageReference Include="AngleSharp" Version="1.8.0-beta.679" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Blaizio.Base\Blaizio.Base.csproj" />
    <ProjectReference Include="..\..\src\Blaizio.Ui\Blaizio.Ui.csproj" />
  </ItemGroup>

</Project>
