<#
.SYNOPSIS
    (Re)generates Blazeo's Tabler icon path data into src/Blazeo.Icons/Icons.<Family>.cs.

.DESCRIPTION
    Ported and modernised from ArcBlazor's Update-ArcIcons.ps1:
      - flattened output: Icons.Outline.Plus directly (no private const + nested All indirection),
      - dropped the per-category files (rarely used; the flat family class is enough),
      - each member is an Icon-valued expression-bodied property carrying its family - typed and,
        crucially, trim-friendly (no static cctor over the family, so unused icons are removed),
      - PowerShell 7 idioms, and a -Source switch to point at an already-downloaded icon set.

    By default it downloads the Tabler Icons repository. Each family folder under icons/
    (outline, filled) becomes a `public static class` of `Icon`-valued static properties.

.PARAMETER Source
    Path to a folder containing per-family icon sub-folders (each holding *.svg). When omitted,
    the Tabler repository is downloaded to a temp folder.

.EXAMPLE
    pwsh ./scripts/Update-BlazeoIcons.ps1
#>
[CmdletBinding()]
param(
    [string]$Source,
    [string]$OutputFolder = (Join-Path $PSScriptRoot '..' 'src' 'Blazeo.Icons'),
    [string]$Namespace = 'Blazeo'
)

$ErrorActionPreference = 'Stop'

function ConvertTo-PascalCase {
    param([string]$Name, [hashtable]$Seen)

    $id = (Get-Culture).TextInfo.ToTitleCase(($Name -replace '[-_]', ' ')) -replace '\s', ''
    if ($id -match '^\d') { $id = "_$id" }

    $base = $id; $n = 1
    while ($Seen.ContainsKey($id)) { $id = "$base$n"; $n++ }
    $Seen[$id] = $true
    return $id
}

function Get-SvgInner {
    param([string]$Svg)
    if ($Svg -match '(?s)<svg[^>]*>(.*)</svg>') {
        ($matches[1].Trim() -replace '\r?\n', ' ' -replace '\s+', ' ' -replace '/>\s+<', '/><').Trim()
    }
}

function Get-TablerIcons {
    $tmp = Join-Path $PSScriptRoot '.tabler-tmp'
    $zip = Join-Path $PSScriptRoot 'tabler.zip'
    if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }

    Write-Host 'Downloading Tabler Icons...'
    Invoke-WebRequest -Uri 'https://github.com/tabler/tabler-icons/archive/refs/heads/main.zip' -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $tmp
    Remove-Item $zip -Force

    $icons = Get-ChildItem -Path $tmp -Directory -Filter 'icons' -Recurse | Select-Object -First 1 -ExpandProperty FullName
    if (-not $icons) { throw 'Could not locate the icons directory in the Tabler download.' }
    return $icons
}

$iconsPath = if ($Source) { $Source } else { Get-TablerIcons }
$generatedBy = "Update-BlazeoIcons.ps1 on $([datetime]::UtcNow.ToString('yyyy-MM-dd', [System.Globalization.CultureInfo]::InvariantCulture))"

foreach ($family in Get-ChildItem -Path $iconsPath -Directory) {
    $familyName = (Get-Culture).TextInfo.ToTitleCase($family.Name)
    $kind = if ($familyName -eq 'Filled') { 'Filled' } else { 'Outline' }
    $seen = @{}
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine("// <auto-generated /> Generated by $generatedBy. Do not edit by hand.")
    [void]$sb.AppendLine("namespace $Namespace;")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('public partial class Icons')
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    /// <summary>$familyName Tabler icons.</summary>")
    [void]$sb.AppendLine("    public static class $familyName")
    [void]$sb.AppendLine('    {')

    $defs = @{}
    foreach ($file in Get-ChildItem -Path $family.FullName -Filter '*.svg') {
        $inner = Get-SvgInner -Svg (Get-Content -Path $file.FullName -Raw)
        if ($inner) {
            $name = ConvertTo-PascalCase -Name $file.BaseName -Seen $seen
            $defs[$name] = $inner
        }
    }

    foreach ($name in ($defs.Keys | Sort-Object)) {
        [void]$sb.AppendLine("        public static Icon $name => new(`"`"`"$($defs[$name])`"`"`", IconKind.$kind);")
    }

    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine('}')

    $outPath = Join-Path $OutputFolder "Icons.$familyName.cs"
    $sb.ToString() | Out-File -FilePath $outPath -Encoding utf8 -NoNewline
    Write-Host "Wrote $($defs.Count) $familyName icons -> $outPath"
}

if (-not $Source) { Remove-Item (Join-Path $PSScriptRoot '.tabler-tmp') -Recurse -Force }
Write-Host 'Done.'
